export const SET_ATM_DATA = 'SET_ATM_DATA';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const TOGGLE_ATM_DETAIL_DIALOG = 'TOGGLE_ATM_DETAIL_DIALOG';
export const TOGGLE_FILTER_OPTION = 'TOGGLE_FILTER_OPTION';
export const TOGGLE_ATM_FILTER_DIALOG = 'TOGGLE_ATM_FILTER_DIALOG';