require('dotenv').config();

module.exports = {
  HSBC_API_ENDPOINT: process.env.HSBC_API_ENDPOINT,
  HSBC_CLIENT_ID: process.env.HSBC_CLIENT_ID,
  HSBC_CLIIENT_SECRET: process.env.HSBC_CLIIENT_SECRET,
  HANG_SENG_API_ENDPOINT: process.env.HANG_SENG_API_ENDPOINT,
  HANG_SENG_CLIENT_ID: process.env.HANG_SENG_CLIENT_ID,
  HANG_SENG_CLIENT_SECRET: process.env.HANG_SENG_CLIENT_SECRET,
  FUBON_API_ENDPOINT: process.env.FUBON_API_ENDPOINT,
  FUBON_CLIENT_ID: process.env.FUBON_CLIENT_ID,
  FUBON_CLIENT_SECRET: process.env.FUBON_CLIENT_SECRET,

  BEA_API_ENDPOINT: process.env.BEA_API_ENDPOINT,
  BEA_CLIENT_ID: process.env.BEA_CLIENT_ID,
  BEA_CLIENT_SECRET: process.env.BEA_CLIENT_SECRET,

  ICBC_API_ENDPOINT: process.env.ICBC_API_ENDPOINT,
  ICBC_CLIENT_ID: process.env.ICBC_CLIENT_ID,
  ICBC_CLIENT_SECRET: process.env.ICBC_CLIENT_SECRET,

  WING_LUNK_API_ENDPOINT: process.env.WING_LUNK_API_ENDPOINT,
  WING_LUNK_CLIENT_ID: process.env.WING_LUNK_CLIENT_ID,
  WING_LUNK_CLIENT_SECRET: process.env.WING_LUNK_CLIENT_SECRET,

  BCH_API_ENDPOINT: process.env.BCH_API_ENDPOINT,
  BCH_CLIENT_ID: process.env.BCH_CLIENT_ID,
  BCH_CLIENT_SECRET: process.env.BCH_CLIENT_SECRET,


  SSL_CERT: process.env.SSL_CERT,
  SSL_KEY: process.env.SSL_KEY,
};
