require('dotenv').config();

module.exports = {
  HSBC_API_ENDPOINT: process.env.HSBC_API_ENDPOINT,
  HSBC_CLIENT_ID: process.env.HSBC_CLIENT_ID,
  HSBC_CLIIENT_SECRET: process.env.HSBC_CLIIENT_SECRET,
  HANG_SENG_API_ENDPOINT: process.env.HANG_SENG_API_ENDPOINT,
  HANG_SENG_CLIENT_ID: process.env.HANG_SENG_CLIENT_ID,
  HANG_SENG_CLIENT_SECRET: process.env.HANG_SENG_CLIENT_SECRET,
  FUBON_API_ENDPOINT: process.env.FUBON_API_ENDPOINT,
  FUBON_CLIENT_ID: process.env.FUBON_CLIENT_ID,
  FUBON_CLIENT_SECRET: process.env.FUBON_CLIENT_SECRET,
  SSL_CERT: process.env.SSL_CERT,
  SSL_KEY: process.env.SSL_KEY,
};
